### ISSUE TITLE
Value too long for type character varying(30)

### ISSUE THREAD

**Issue by cimar** [PublicI/fec-loader#42] opened 2018-03-16 21:14 UTC
{ SequelizeDatabaseError: value too long for type character varying(30)
    at Query.formatError (/Users/rosie/Documents/fec-model/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
    at Query.<anonymous> (/Users/rosie/Documents/fec-model/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
    at Query.emit (events.js:180:13)
    at Query.handleError (/Users/rosie/Documents/fec-model/node_modules/pg/lib/query.js:125:8)
    at Connection.<anonymous> (/Users/rosie/Documents/fec-model/node_modules/pg/lib/client.js:171:26)
    at Connection.emit (events.js:180:13)
    at Socket.<anonymous> (/Users/rosie/Documents/fec-model/node_modules/pg/lib/connection.js:109:12)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:578:20)
  name: 'SequelizeDatabaseError',
  message: 'value too long for type character varying(30)',
  parent: 
   { error: value too long for type character varying(30)
    at Connection.parseE (/Users/rosie/Documents/fec-model/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/Users/rosie/Documents/fec-model/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/Users/rosie/Documents/fec-model/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:578:20)
     name: 'error',
     length: 98,
     severity: 'ERROR',
     code: '22001',
     detail: undefined,
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'varchar.c',
     line: '624',
     routine: 'varchar',
     sql: 'INSERT INTO "fec_contributions" ("id","filing_id","form_type","filer_committee_id_number","contributor_organization_name","contributor_last_name","contributor_first_name","contributor_middle_name","contributor_prefix","contributor_suffix","contributor_street_1","contributor_street_2","contributor_city","contributor_state","contributor_zip_code","election_code","election_other_description","contribution_date","contribution_amount","contribution_aggregate","contributor_employer","contributor_occupation","donor_committee_fec_id","memo_text_description") VALUES (DEFAULT,\'997772\',\'SA11A1\',\'C00437889\',NULL,\'SMITH\',\'SONDRA\',\'J\',NULL,NULL,\'2914 BAMLET RD\',NULL,\'ROYAL OAK\',\'MI\',\'480732979\',\'DIRECTOR OF CORPORATE MARKETING\',\'P\',\'2014-04-30 04:00:00.000 +00:00\',\'      500.00\',\'2014\',\'BLUE CROSS BLUE SHIELD OF MICHIGAN\',NULL,NULL,\'      500.00\');' },
  original: 
   { error: value too long for type character varying(30)
    at Connection.parseE (/Users/rosie/Documents/fec-model/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/Users/rosie/Documents/fec-model/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/Users/rosie/Documents/fec-model/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:578:20)
     name: 'error',
     length: 98,
     severity: 'ERROR',
     code: '22001',
     detail: undefined,
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'varchar.c',
     line: '624',
     routine: 'varchar',
     sql: 'INSERT INTO "fec_contributions" ("id","filing_id","form_type","filer_committee_id_number","contributor_organization_name","contributor_last_name","contributor_first_name","contributor_middle_name","contributor_prefix","contributor_suffix","contributor_street_1","contributor_street_2","contributor_city","contributor_state","contributor_zip_code","election_code","election_other_description","contribution_date","contribution_amount","contribution_aggregate","contributor_employer","contributor_occupation","donor_committee_fec_id","memo_text_description") VALUES (DEFAULT,\'997772\',\'SA11A1\',\'C00437889\',NULL,\'SMITH\',\'SONDRA\',\'J\',NULL,NULL,\'2914 BAMLET RD\',NULL,\'ROYAL OAK\',\'MI\',\'480732979\',\'DIRECTOR OF CORPORATE MARKETING\',\'P\',\'2014-04-30 04:00:00.000 +00:00\',\'      500.00\',\'2014\',\'BLUE CROSS BLUE SHIELD OF MICHIGAN\',NULL,NULL,\'      500.00\');' },
  sql: 'INSERT INTO "fec_contributions" ("id","filing_id","form_type","filer_committee_id_number","contributor_organization_name","contributor_last_name","contributor_first_name","contributor_middle_name","contributor_prefix","contributor_suffix","contributor_street_1","contributor_street_2","contributor_city","contributor_state","contributor_zip_code","election_code","election_other_description","contribution_date","contribution_amount","contribution_aggregate","contributor_employer","contributor_occupation","donor_committee_fec_id","memo_text_description") VALUES (DEFAULT,\'997772\',\'SA11A1\',\'C00437889\',NULL,\'SMITH\',\'SONDRA\',\'J\',NULL,NULL,\'2914 BAMLET RD\',NULL,\'ROYAL OAK\',\'MI\',\'480732979\',\'DIRECTOR OF CORPORATE MARKETING\',\'P\',\'2014-04-30 04:00:00.000 +00:00\',\'      500.00\',\'2014\',\'BLUE CROSS BLUE SHIELD OF MICHIGAN\',NULL,NULL,\'      500.00\');' }

**Comment by chriszs** [comment] 2018-03-16 21:48
closed as duplicate of #29

**Closed by chriszs** 2018-03-16 21:48 UTC
