### ISSUE TITLE
Foreign key constraint error

### ISSUE THREAD

**Issue by cimar** [PublicI/fec-loader#43] opened 2018-03-16 21:15 UTC
{ SequelizeForeignKeyConstraintError: insert or update on table "fec_contributions" violates foreign key constraint "fec_contributions_filing_id_fkey"
    at Query.formatError (/Users/rosie/Documents/fec-model/node_modules/sequelize/lib/dialects/postgres/query.js:296:14)
    at Query.<anonymous> (/Users/rosie/Documents/fec-model/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
    at Query.emit (events.js:180:13)
    at Query.handleError (/Users/rosie/Documents/fec-model/node_modules/pg/lib/query.js:125:8)
    at Connection.<anonymous> (/Users/rosie/Documents/fec-model/node_modules/pg/lib/client.js:171:26)
    at Connection.emit (events.js:180:13)
    at Socket.<anonymous> (/Users/rosie/Documents/fec-model/node_modules/pg/lib/connection.js:109:12)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:578:20)
  name: 'SequelizeForeignKeyConstraintError',
  message: 'insert or update on table "fec_contributions" violates foreign key constraint "fec_contributions_filing_id_fkey"',
  parent: 
   { error: insert or update on table "fec_contributions" violates foreign key constraint "fec_contributions_filing_id_fkey"
    at Connection.parseE (/Users/rosie/Documents/fec-model/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/Users/rosie/Documents/fec-model/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/Users/rosie/Documents/fec-model/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:578:20)
     name: 'error',
     length: 307,
     severity: 'ERROR',
     code: '23503',
     detail: 'Key (filing_id)=(997646) is not present in table "fec_filings".',
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: 'public',
     table: 'fec_contributions',
     column: undefined,
     dataType: undefined,
     constraint: 'fec_contributions_filing_id_fkey',
     file: 'ri_triggers.c',
     line: '3324',
     routine: 'ri_ReportViolation',
     sql: 'INSERT INTO "fec_contributions" ("id","filing_id","form_type","filer_committee_id_number","contributor_organization_name","contributor_last_name","contributor_first_name","contributor_middle_name","contributor_prefix","contributor_suffix","contributor_street_1","contributor_street_2","contributor_city","contributor_state","contributor_zip_code","election_code","election_other_description","contribution_date","contribution_amount","contribution_aggregate","contributor_employer","contributor_occupation","donor_committee_fec_id","memo_text_description") VALUES (DEFAULT,\'997646\',\'SA11A1\',\'C00547570\',NULL,\'HAUCK\',\'MEGAN\',NULL,NULL,NULL,\'133 DUDDINGTON PLACE SE\',NULL,\'WASHINGTON\',\'DC\',\'200032625\',\'CONSULTANT\',\'G\',\'2014-09-09 04:00:00.000 +00:00\',\'     1000.00\',\'2014\',\'NATHANSON\',NULL,NULL,\'     1000.00\');' },
  original: 
   { error: insert or update on table "fec_contributions" violates foreign key constraint "fec_contributions_filing_id_fkey"
    at Connection.parseE (/Users/rosie/Documents/fec-model/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/Users/rosie/Documents/fec-model/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/Users/rosie/Documents/fec-model/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:578:20)
     name: 'error',
     length: 307,
     severity: 'ERROR',
     code: '23503',
     detail: 'Key (filing_id)=(997646) is not present in table "fec_filings".',
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: 'public',
     table: 'fec_contributions',
     column: undefined,
     dataType: undefined,
     constraint: 'fec_contributions_filing_id_fkey',
     file: 'ri_triggers.c',
     line: '3324',
     routine: 'ri_ReportViolation',
     sql: 'INSERT INTO "fec_contributions" ("id","filing_id","form_type","filer_committee_id_number","contributor_organization_name","contributor_last_name","contributor_first_name","contributor_middle_name","contributor_prefix","contributor_suffix","contributor_street_1","contributor_street_2","contributor_city","contributor_state","contributor_zip_code","election_code","election_other_description","contribution_date","contribution_amount","contribution_aggregate","contributor_employer","contributor_occupation","donor_committee_fec_id","memo_text_description") VALUES (DEFAULT,\'997646\',\'SA11A1\',\'C00547570\',NULL,\'HAUCK\',\'MEGAN\',NULL,NULL,NULL,\'133 DUDDINGTON PLACE SE\',NULL,\'WASHINGTON\',\'DC\',\'200032625\',\'CONSULTANT\',\'G\',\'2014-09-09 04:00:00.000 +00:00\',\'     1000.00\',\'2014\',\'NATHANSON\',NULL,NULL,\'     1000.00\');' },
  sql: 'INSERT INTO "fec_contributions" ("id","filing_id","form_type","filer_committee_id_number","contributor_organization_name","contributor_last_name","contributor_first_name","contributor_middle_name","contributor_prefix","contributor_suffix","contributor_street_1","contributor_street_2","contributor_city","contributor_state","contributor_zip_code","election_code","election_other_description","contribution_date","contribution_amount","contribution_aggregate","contributor_employer","contributor_occupation","donor_committee_fec_id","memo_text_description") VALUES (DEFAULT,\'997646\',\'SA11A1\',\'C00547570\',NULL,\'HAUCK\',\'MEGAN\',NULL,NULL,NULL,\'133 DUDDINGTON PLACE SE\',NULL,\'WASHINGTON\',\'DC\',\'200032625\',\'CONSULTANT\',\'G\',\'2014-09-09 04:00:00.000 +00:00\',\'     1000.00\',\'2014\',\'NATHANSON\',NULL,NULL,\'     1000.00\');',
  fields: null,
  table: 'fec_contributions',
  value: undefined,
  index: 'fec_contributions_filing_id_fkey' }

**Comment by chriszs** [comment] 2018-03-16 21:45
closed as duplicate of #29

**Closed by chriszs** 2018-03-16 21:45 UTC

**Comment by maixuanhan** [comment] 2021-04-01 09:45
So what did cause the problem? Why we have the data in the foreign table (Key (filing_id)=(997646)) but cannot make reference to it?
